"""Create memory embeddings table

Revision ID: 104387c596e4
Revises: 8d794f3f6ec2
Create Date: 2026-08-05 17:10:40.893307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104387c596e4'
down_revision = '8d794f3f6ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_embeddings')
    # ### end Alembic commands ###
