"""Add retrieval_count to memories

Revision ID: 1a6ca2dfc57d
Revises: 341d2475fcb8
Create Date: 2026-07-23 10:49:10.851923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6ca2dfc57d'
down_revision = '341d2475fcb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retrieval_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_column('retrieval_count')

    # ### end Alembic commands ###
