"""add entities table

Revision ID: 694bbacfbbdd
Revises: 9010a32eb16d
Create Date: 2026-08-16 20:03:05.266857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694bbacfbbdd'
down_revision = '9010a32eb16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entities')
    # ### end Alembic commands ###
