"""add relationship table

Revision ID: 8d794f3f6ec2
Revises: 1a6ca2dfc57d
Create Date: 2026-07-25 13:25:47.482614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d794f3f6ec2'
down_revision = '1a6ca2dfc57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=True),
    sa.Column('familiarity', sa.Integer(), nullable=True),
    sa.Column('comfort', sa.Integer(), nullable=True),
    sa.Column('humor', sa.Integer(), nullable=True),
    sa.Column('respect', sa.Integer(), nullable=True),
    sa.Column('emotional_closeness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    # ### end Alembic commands ###
